import Head from 'next/head'
import Main from '../components/Main'
import ReactTooltip from "react-tooltip";

export default function Home() {

  return (
    <div>
      <Head>
        <title>Circa Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ReactTooltip />
      <main className='main'>
        <Main />
      </main>

    </div>
  )
}